#pragma once
#include "expression_tokenizer.h"

//This file defines the ExpressionParser class which is
//used to evaluate Tokens generated by the Tokenizer class.

namespace expression_parser
{
	using namespace tokenizer;

	class ExpressionParser
	{
	private:
		//Data Members
		Tokenizer mcTokenizer;

		//Private Member Functions
		double add_expression(bool b_next_token);
		double mult_expression(bool b_next_token);
		double primary(bool b_next_token);

	public:
		//Constructors
		ExpressionParser() : mcTokenizer{ Tokenizer() } {}
		ExpressionParser(std::istringstream& sstream) : mcTokenizer{ Tokenizer(sstream) } {}

		//Public Member Functions
		void parse();
	};
}
